### ISSUE TITLE
Nuget Package

### ISSUE THREAD

**Issue by wahmedswl** [SaxxonPike/NextLevelSeven#1]
Hi, it would be great if Nuget package is published.

Thanks

**Comment by SaxxonPike** [comment]
Before releasing to NuGet, I will be combing through features to make sure they are not incomplete. Only complete features should make it to the package. Thanks for your interest!

**Comment by wahmedswl** [comment]
It would be great if nuget packages are published as it will help in getting feedback quickly. I have made some changes for Paket + Cake support, i will create pull request 

 Thanks
