### ISSUE TITLE
Add NetStandard 2.0

### ISSUE THREAD

**Issue by kfrancis** [SaxxonPike/NextLevelSeven#4]
Hey,

Question - I'd like to add NetStandard support for your library. I've already done all the work to add multi-targeting to your library. Would you be ok with that pull request? The actual change is simple, I did have to reconfigure the test project but all tests are passing in both full .NET Framework and .NET Core now.

**Comment by SaxxonPike** [comment]
This sounds great! Put in the request and I'll look it over. Thanks for your efforts :)

**Comment by SaxxonPike** [comment]
The latest commit should add this to the list of targeted frameworks. There will need to be further work to bring the test project's NUnit up to 3 so that we can also run the tests on .NET Standard 2.0. However, as-is, the library compiles for both .NET 4.5 and .NET Standard 2.0.

**Comment by kfrancis** [comment]
I can do that, sorry for the delay.

**Comment by kfrancis** [comment]
If you do end up accepting that pull request, would you mind pushing it out to nuget pretty please?

**Comment by SaxxonPike** [comment]
Going to put this out as 1.0.1. For *long story* reasons.

**Comment by SaxxonPike** [comment]
@kfrancis  It looks like this was approved and indexed, and there are some downloads already. So, I'm going to assume all is well. If any further issues crop up, let's reopen new issues more appropriate to whatever's up. Thanks for everything!

It has been published at:
https://www.nuget.org/packages/NextLevelSeven/
